### ISSUE TITLE
stride is super fun

### ISSUE THREAD

**Issue by rasheelprogrammer** [CrankySupertoon01/Toontown-2#1]

**Comment by rasheelprogrammer** [comment]
![image](https://user-images.githubusercontent.com/33942724/43360248-0c41f156-92bb-11e8-9e19-8511cb46ad74.png)

**Comment by ghost** [comment]
Nice meme game 10/10

**Comment by CrankySupertoonArchive** [comment]
Im just going to close this DM. That you magic

**Comment by CrankySupertoonArchive** [comment]
And we have stated we are using stride

**Comment by rasheelprogrammer** [comment]
why are you stealing ttcc playground names that you dont have the right to use?

**Comment by CrankySupertoonArchive** [comment]
The streets were renamed, and im not slamed by disney
